2025-04-05 23:23:23,068 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:23:23,235 - WARNING - Updates were skipped successfully.
2025-04-05 23:23:23,236 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:23:23,236 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:23:23,236 - INFO - Scheduler started
2025-04-05 23:23:23,236 - INFO - Scheduler started with optimized configuration
2025-04-05 23:23:23,236 - INFO - Бот запущен.
2025-04-05 23:23:23,236 - INFO - Start polling.
2025-04-05 23:23:37,608 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:23:37,608 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:23:37,608 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:23:44,186 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:23:44,187 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:23:44,187 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:24:04,503 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:24:04,503 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:24:04,503 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:24:25,611 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:25:23 MSK)" was missed by 0:00:02.375433
2025-04-05 23:25:25,614 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:26:23 MSK)" was missed by 0:00:02.377876
2025-04-05 23:26:25,623 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:27:23 MSK)" was missed by 0:00:02.386928
2025-04-05 23:26:53,999 - INFO - Stop polling...
2025-04-05 23:26:53,999 - WARNING - Goodbye!
2025-04-05 23:26:55,799 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:26:55,986 - WARNING - Updates were skipped successfully.
2025-04-05 23:26:55,990 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:26:55,991 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:26:55,991 - INFO - Scheduler started
2025-04-05 23:26:55,991 - INFO - Scheduler started with optimized configuration
2025-04-05 23:26:55,991 - INFO - Бот запущен.
2025-04-05 23:26:55,991 - INFO - Start polling.
2025-04-05 23:27:08,749 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-05 23:27:12,881 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:27:12,882 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:27:18,554 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:27:18,554 - INFO - Пользователь 1999873173 уже существует
2025-04-05 23:27:49,080 - INFO - Stop polling...
2025-04-05 23:27:49,080 - WARNING - Goodbye!
2025-04-05 23:27:50,380 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:27:50,539 - WARNING - Updates were skipped successfully.
2025-04-05 23:27:50,542 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:27:50,542 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:27:50,542 - INFO - Scheduler started
2025-04-05 23:27:50,542 - INFO - Scheduler started with optimized configuration
2025-04-05 23:27:50,542 - INFO - Бот запущен.
2025-04-05 23:27:50,543 - INFO - Start polling.
2025-04-05 23:27:53,793 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:27:53,793 - INFO - Пользователь 1999873173 уже существует
2025-04-05 23:28:03,250 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:28:03,250 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:28:11,611 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:28:11,612 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:28:11,612 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:28:23,712 - INFO - Cleared learned words for user 1999873173
2025-04-05 23:28:23,712 - INFO - Dictionary cleared for user 1999873173 due to set change
2025-04-05 23:28:23,712 - INFO - Resetting daily words cache for user 1999873173
2025-04-05 23:28:23,712 - INFO - Cache successfully reset for user 1999873173
2025-04-05 23:28:44,918 - INFO - Stop polling...
2025-04-05 23:28:44,919 - WARNING - Goodbye!
2025-04-05 23:53:05,043 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:53:05,216 - WARNING - Updates were skipped successfully.
2025-04-05 23:53:05,218 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:53:05,218 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:53:05,218 - INFO - Scheduler started
2025-04-05 23:53:05,218 - INFO - Scheduler started with optimized configuration
2025-04-05 23:53:05,218 - INFO - Бот запущен.
2025-04-05 23:53:05,218 - INFO - Start polling.
2025-04-05 23:53:10,912 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:53:10,912 - INFO - Пользователь 1999873173 уже существует
2025-04-05 23:54:05,537 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-05 23:54:05,537 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:54:05,537 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:54:05,539 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:54:05,539 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:54:08,653 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:55:05 MSK)" was missed by 0:00:03.434840
2025-04-05 23:54:30,206 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-05 23:54:30,206 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:54:30,206 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:54:41,737 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-05 23:54:41,737 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:54:41,737 - INFO - Подготовлено 3 слов для квиза пользователя 1999873173
2025-04-05 23:54:53,451 - INFO - Stop polling...
2025-04-05 23:54:53,452 - WARNING - Goodbye!
2025-04-05 23:54:54,547 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:54:54,697 - WARNING - Updates were skipped successfully.
2025-04-05 23:54:54,699 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:54:54,699 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:54:54,699 - INFO - Scheduler started
2025-04-05 23:54:54,699 - INFO - Scheduler started with optimized configuration
2025-04-05 23:54:54,699 - INFO - Бот запущен.
2025-04-05 23:54:54,700 - INFO - Start polling.
2025-04-05 23:55:03,650 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:03,650 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:12,859 - INFO - Resetting daily words cache for user 1999873173
2025-04-05 23:55:12,859 - INFO - Cache successfully reset for user 1999873173
2025-04-05 23:55:22,311 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:22,311 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:37,348 - INFO - Resetting daily words cache for user 1999873173
2025-04-05 23:55:37,348 - INFO - Cache successfully reset for user 1999873173
2025-04-05 23:55:42,049 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-143' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-05 23:55:53,077 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:53,077 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:55:56,051 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-05 23:55:56,052 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:55:56,052 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-05 23:55:58,148 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:56:54 MSK)" was missed by 0:00:03.449665
2025-04-05 23:56:58,468 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:57:54 MSK)" was missed by 0:00:03.769745
2025-04-05 23:57:00,217 - INFO - Stop polling...
2025-04-05 23:57:00,217 - WARNING - Goodbye!
2025-04-05 23:57:02,399 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:57:02,552 - WARNING - Updates were skipped successfully.
2025-04-05 23:57:02,554 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:57:02,555 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:57:02,555 - INFO - Scheduler started
2025-04-05 23:57:02,555 - INFO - Scheduler started with optimized configuration
2025-04-05 23:57:02,555 - INFO - Бот запущен.
2025-04-05 23:57:02,555 - INFO - Start polling.
2025-04-05 23:57:06,079 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:57:06,079 - INFO - Пользователь 1999873173 уже существует
2025-04-05 23:57:10,045 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:57:10,045 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:57:10,046 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:57:10,047 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:57:10,047 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-05 23:57:52,617 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:57:52,617 - INFO - Пользователь 1999873173 уже существует
2025-04-05 23:57:58,373 - INFO - У пользователя 1999873173 есть 1 выученных слов
2025-04-05 23:57:58,373 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-05 23:57:58,373 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-05 23:58:06,526 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-05 23:59:02 MSK)" was missed by 0:00:03.972243
2025-04-05 23:58:08,463 - INFO - Stop polling...
2025-04-05 23:58:08,463 - WARNING - Goodbye!
2025-04-05 23:59:39,826 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-05 23:59:39,977 - WARNING - Updates were skipped successfully.
2025-04-05 23:59:39,978 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-05 23:59:39,978 - INFO - Added job "scheduler_job" to job store "default"
2025-04-05 23:59:39,978 - INFO - Scheduler started
2025-04-05 23:59:39,978 - INFO - Scheduler started with optimized configuration
2025-04-05 23:59:39,978 - INFO - Бот запущен.
2025-04-05 23:59:39,979 - INFO - Start polling.
2025-04-05 23:59:42,889 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-05 23:59:42,897 - INFO - Added new user with chat_id: 1999873173 with default set: At Home
2025-04-05 23:59:42,898 - INFO - Добавлен новый пользователь с chat_id 1999873173
2025-04-05 23:59:42,898 - INFO - Установлен базовый сет At Home для нового пользователя 1999873173
2025-04-05 23:59:44,913 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-05 23:59:44,913 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:00:11,555 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 00:00:11,555 - INFO - Cache successfully reset for user 1999873173
2025-04-06 00:00:25,702 - INFO - Cleared learned words for user 1999873173
2025-04-06 00:00:25,702 - INFO - Dictionary cleared for user 1999873173 due to set change from 'At Home' to 'Animals and Pets'
2025-04-06 00:00:28,235 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:00:28,235 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:00:30,321 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 00:00:30,321 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 00:00:30,321 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-06 00:00:43,672 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:01:39 MSK)" was missed by 0:00:03.694533
2025-04-06 00:01:12,521 - INFO - Stop polling...
2025-04-06 00:01:12,522 - WARNING - Goodbye!
2025-04-06 00:01:21,113 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:01:21,269 - WARNING - Updates were skipped successfully.
2025-04-06 00:01:21,275 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:01:21,275 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:01:21,275 - INFO - Scheduler started
2025-04-06 00:01:21,276 - INFO - Scheduler started with optimized configuration
2025-04-06 00:01:21,276 - INFO - Бот запущен.
2025-04-06 00:01:21,276 - INFO - Start polling.
2025-04-06 00:01:27,283 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:01:27,284 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:01:28,617 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:01:28,617 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:01:34,623 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 00:01:34,624 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 00:01:34,624 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-06 00:02:16,176 - INFO - Stop polling...
2025-04-06 00:02:16,177 - WARNING - Goodbye!
2025-04-06 00:02:34,443 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:02:34,609 - WARNING - Updates were skipped successfully.
2025-04-06 00:02:34,611 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:02:34,612 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:02:34,612 - INFO - Scheduler started
2025-04-06 00:02:34,612 - INFO - Scheduler started with optimized configuration
2025-04-06 00:02:34,612 - INFO - Бот запущен.
2025-04-06 00:02:34,612 - INFO - Start polling.
2025-04-06 00:02:39,428 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:02:39,428 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:02:40,662 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:02:40,662 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:02:44,339 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 00:02:44,339 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 00:02:44,339 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-06 00:03:15,739 - INFO - Stop polling...
2025-04-06 00:03:15,739 - WARNING - Goodbye!
2025-04-06 00:04:26,001 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:04:26,153 - WARNING - Updates were skipped successfully.
2025-04-06 00:04:26,155 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:04:26,155 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:04:26,155 - INFO - Scheduler started
2025-04-06 00:04:26,155 - INFO - Scheduler started with optimized configuration
2025-04-06 00:04:26,155 - INFO - Бот запущен.
2025-04-06 00:04:26,155 - INFO - Start polling.
2025-04-06 00:04:29,128 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 00:04:29,128 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:04:29,128 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:04:29,130 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 00:04:29,130 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-06 00:05:29,682 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:06:26 MSK)" was missed by 0:00:03.527129
2025-04-06 00:06:29,679 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:07:26 MSK)" was missed by 0:00:03.524121
2025-04-06 00:07:27,924 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:08:26 MSK)" was missed by 0:00:01.769628
2025-04-06 00:08:29,688 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:09:26 MSK)" was missed by 0:00:03.533056
2025-04-06 00:09:29,861 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:10:26 MSK)" was missed by 0:00:03.706042
2025-04-06 00:10:09,383 - INFO - Stop polling...
2025-04-06 00:10:09,384 - WARNING - Goodbye!
2025-04-06 00:10:10,878 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:10:11,039 - WARNING - Updates were skipped successfully.
2025-04-06 00:10:11,041 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:10:11,043 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:10:11,043 - INFO - Scheduler started
2025-04-06 00:10:11,043 - INFO - Scheduler started with optimized configuration
2025-04-06 00:10:11,043 - INFO - Бот запущен.
2025-04-06 00:10:11,043 - INFO - Start polling.
2025-04-06 00:10:22,331 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:10:22,331 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:10:23,794 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 00:10:23,794 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:10:23,795 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:10:23,795 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 00:10:23,795 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-06 00:11:08,876 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 00:11:08,876 - INFO - Cache successfully reset for user 1999873173
2025-04-06 00:11:14,414 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:12:11 MSK)" was missed by 0:00:03.373094
2025-04-06 00:11:40,253 - INFO - Stop polling...
2025-04-06 00:11:40,254 - WARNING - Goodbye!
2025-04-06 00:14:01,055 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:14:01,205 - WARNING - Updates were skipped successfully.
2025-04-06 00:14:01,206 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:14:01,207 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:14:01,207 - INFO - Scheduler started
2025-04-06 00:14:01,207 - INFO - Scheduler started with optimized configuration
2025-04-06 00:14:01,207 - INFO - Бот запущен.
2025-04-06 00:14:01,207 - INFO - Start polling.
2025-04-06 00:14:07,204 - INFO - Stop polling...
2025-04-06 00:14:07,205 - WARNING - Goodbye!
2025-04-06 00:18:56,599 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:18:56,768 - WARNING - Updates were skipped successfully.
2025-04-06 00:18:56,771 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:18:56,772 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:18:56,772 - INFO - Scheduler started
2025-04-06 00:18:56,772 - INFO - Scheduler started with optimized configuration
2025-04-06 00:18:56,772 - INFO - Бот запущен.
2025-04-06 00:18:56,772 - INFO - Start polling.
2025-04-06 00:19:02,756 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:19:02,756 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:19:04,127 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:19:04,127 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:19:06,671 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-29' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'state_current_index' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 500, in handle_memorize_set
    await send_learning_test_question(chat_id, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 514, in send_learning_test_question
    question = state["questions"][state_current_index]
                                  ^^^^^^^^^^^^^^^^^^^
NameError: name 'state_current_index' is not defined
2025-04-06 00:19:08,971 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-33' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'state_current_index' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 500, in handle_memorize_set
    await send_learning_test_question(chat_id, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 514, in send_learning_test_question
    question = state["questions"][state_current_index]
                                  ^^^^^^^^^^^^^^^^^^^
NameError: name 'state_current_index' is not defined
2025-04-06 00:19:17,426 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 00:19:17,427 - INFO - Cache successfully reset for user 1999873173
2025-04-06 00:19:22,328 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-82' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'state_current_index' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 500, in handle_memorize_set
    await send_learning_test_question(chat_id, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 514, in send_learning_test_question
    question = state["questions"][state_current_index]
                                  ^^^^^^^^^^^^^^^^^^^
NameError: name 'state_current_index' is not defined
2025-04-06 00:19:23,770 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-86' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'state_current_index' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 500, in handle_memorize_set
    await send_learning_test_question(chat_id, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 514, in send_learning_test_question
    question = state["questions"][state_current_index]
                                  ^^^^^^^^^^^^^^^^^^^
NameError: name 'state_current_index' is not defined
2025-04-06 00:19:32,087 - INFO - Stop polling...
2025-04-06 00:19:32,087 - WARNING - Goodbye!
2025-04-06 00:19:34,185 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:19:34,342 - WARNING - Updates were skipped successfully.
2025-04-06 00:19:34,347 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:19:34,349 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:19:34,349 - INFO - Scheduler started
2025-04-06 00:19:34,349 - INFO - Scheduler started with optimized configuration
2025-04-06 00:19:34,349 - INFO - Бот запущен.
2025-04-06 00:19:34,350 - INFO - Start polling.
2025-04-06 00:19:37,109 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'state_current_index' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 500, in handle_memorize_set
    await send_learning_test_question(chat_id, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 514, in send_learning_test_question
    question = state["questions"][state_current_index]
                                  ^^^^^^^^^^^^^^^^^^^
NameError: name 'state_current_index' is not defined
2025-04-06 00:20:38,381 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:21:34 MSK)" was missed by 0:00:04.033472
2025-04-06 00:21:36,361 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:22:34 MSK)" was missed by 0:00:02.013500
2025-04-06 00:22:32,530 - INFO - Stop polling...
2025-04-06 00:22:32,530 - WARNING - Goodbye!
2025-04-06 00:22:34,729 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:22:34,884 - WARNING - Updates were skipped successfully.
2025-04-06 00:22:34,888 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:22:34,888 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:22:34,888 - INFO - Scheduler started
2025-04-06 00:22:34,889 - INFO - Scheduler started with optimized configuration
2025-04-06 00:22:34,889 - INFO - Бот запущен.
2025-04-06 00:22:34,889 - INFO - Start polling.
2025-04-06 00:22:56,777 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:22:56,778 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:22:58,199 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:22:58,199 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:23:05,069 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 00:23:05,069 - INFO - Cache successfully reset for user 1999873173
2025-04-06 00:23:38,795 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:24:34 MSK)" was missed by 0:00:03.907658
2025-04-06 00:24:34,602 - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-04-06 00:24:38,853 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:25:34 MSK)" was missed by 0:00:03.965532
2025-04-06 00:24:44,420 - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-04-06 00:24:54,822 - INFO - Stop polling...
2025-04-06 00:24:54,822 - WARNING - Goodbye!
2025-04-06 00:24:55,947 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:24:56,106 - WARNING - Updates were skipped successfully.
2025-04-06 00:24:56,108 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:24:56,109 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:24:56,109 - INFO - Scheduler started
2025-04-06 00:24:56,109 - INFO - Scheduler started with optimized configuration
2025-04-06 00:24:56,109 - INFO - Бот запущен.
2025-04-06 00:24:56,109 - INFO - Start polling.
2025-04-06 00:25:30,335 - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-04-06 00:25:44,916 - INFO - Stop polling...
2025-04-06 00:25:44,917 - WARNING - Goodbye!
2025-04-06 00:26:11,045 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:26:11,197 - WARNING - Updates were skipped successfully.
2025-04-06 00:26:11,201 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:26:11,202 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:26:11,202 - INFO - Scheduler started
2025-04-06 00:26:11,203 - INFO - Scheduler started with optimized configuration
2025-04-06 00:26:11,203 - INFO - Бот запущен.
2025-04-06 00:26:11,203 - INFO - Start polling.
2025-04-06 00:26:18,175 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 376, in handle_memorize_set
    await callback.message.edit_text(
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-04-06 00:26:29,860 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-44' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-06 00:27:15,024 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:28:11 MSK)" was missed by 0:00:03.823229
2025-04-06 00:28:15,034 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:29:11 MSK)" was missed by 0:00:03.833111
2025-04-06 00:28:56,575 - INFO - Stop polling...
2025-04-06 00:28:56,575 - WARNING - Goodbye!
2025-04-06 00:28:57,519 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:28:57,679 - WARNING - Updates were skipped successfully.
2025-04-06 00:28:57,685 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:28:57,686 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:28:57,686 - INFO - Scheduler started
2025-04-06 00:28:57,686 - INFO - Scheduler started with optimized configuration
2025-04-06 00:28:57,686 - INFO - Бот запущен.
2025-04-06 00:28:57,686 - INFO - Start polling.
2025-04-06 00:29:09,234 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:29:09,234 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:29:17,503 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 00:29:17,503 - INFO - Cache successfully reset for user 1999873173
2025-04-06 00:29:51,666 - INFO - Получена команда /start от chat_id: 380675615
2025-04-06 00:29:51,666 - INFO - Пользователь 380675615 уже существует
2025-04-06 00:29:52,608 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-154' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-06 00:29:53,949 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-157' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-06 00:30:01,492 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:30:57 MSK)" was missed by 0:00:03.807419
2025-04-06 00:30:10,865 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:30:10,865 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:30:19,825 - INFO - У пользователя 380675615 есть 0 выученных слов
2025-04-06 00:30:19,825 - INFO - Пользователь 380675615 в режиме повторения: False
2025-04-06 00:30:19,825 - INFO - Подготовлено 3 слов для квиза пользователя 380675615
2025-04-06 00:31:00,317 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-369' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/settings.py", line 160, in process_settings_choice_callback
    await process_settings_mysettings(callback, bot)
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/settings.py", line 575, in process_settings_mysettings
    await callback.message.edit_text(
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-04-06 00:31:01,401 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:31:57 MSK)" was missed by 0:00:03.716355
2025-04-06 00:31:07,103 - INFO - Resetting daily words cache for user 380675615
2025-04-06 00:31:07,103 - INFO - Cache successfully reset for user 380675615
2025-04-06 00:31:08,740 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:31:28,690 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:31:58,652 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:32:01,459 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:32:57 MSK)" was missed by 0:00:03.774990
2025-04-06 00:32:05,559 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:32:42,814 - INFO - Cleared learned words for user 380675615
2025-04-06 00:32:42,815 - INFO - Dictionary cleared for user 380675615 due to set change
2025-04-06 00:32:59,646 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:33:57 MSK)" was missed by 0:00:01.961989
2025-04-06 00:33:37,119 - INFO - Stop polling...
2025-04-06 00:33:37,120 - WARNING - Goodbye!
2025-04-06 00:33:57,691 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:33:57,847 - WARNING - Updates were skipped successfully.
2025-04-06 00:33:57,852 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:33:57,854 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:33:57,854 - INFO - Scheduler started
2025-04-06 00:33:57,854 - INFO - Scheduler started with optimized configuration
2025-04-06 00:33:57,854 - INFO - Бот запущен.
2025-04-06 00:33:57,855 - INFO - Start polling.
2025-04-06 00:34:00,495 - INFO - Получена команда /start от chat_id: 380675615
2025-04-06 00:34:00,507 - INFO - Added new user with chat_id: 380675615 with default set: At Home
2025-04-06 00:34:00,507 - INFO - Добавлен новый пользователь с chat_id 380675615
2025-04-06 00:34:00,507 - INFO - Установлен базовый сет At Home для нового пользователя 380675615
2025-04-06 00:34:02,806 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:34:02,807 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:34:08,652 - INFO - Cleared learned words for user 380675615
2025-04-06 00:34:08,652 - INFO - Dictionary cleared for user 380675615 due to set change from 'At Home' to 'Animals and Pets'
2025-04-06 00:34:08,652 - INFO - Resetting daily words cache for user 380675615
2025-04-06 00:34:08,652 - INFO - Cache successfully reset for user 380675615
2025-04-06 00:34:31,602 - INFO - У пользователя 380675615 есть 0 выученных слов
2025-04-06 00:34:31,603 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:34:31,603 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:34:31,604 - INFO - Пользователь 380675615 в режиме повторения: False
2025-04-06 00:34:31,604 - INFO - Подготовлено 5 слов для квиза пользователя 380675615
2025-04-06 00:35:01,618 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:35:57 MSK)" was missed by 0:00:03.765968
2025-04-06 00:35:50,184 - INFO - Resetting daily words cache for user 380675615
2025-04-06 00:35:50,184 - INFO - Cache successfully reset for user 380675615
2025-04-06 00:35:51,564 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:35:54,005 - ERROR - Unexpected error in process_my_sets for user 380675615: Button_data_invalid
2025-04-06 00:36:01,572 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:36:57 MSK)" was missed by 0:00:03.720485
2025-04-06 00:36:04,099 - INFO - Stop polling...
2025-04-06 00:36:04,099 - WARNING - Goodbye!
2025-04-06 00:36:23,132 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:36:23,289 - WARNING - Updates were skipped successfully.
2025-04-06 00:36:23,291 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:36:23,292 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:36:23,292 - INFO - Scheduler started
2025-04-06 00:36:23,292 - INFO - Scheduler started with optimized configuration
2025-04-06 00:36:23,292 - INFO - Бот запущен.
2025-04-06 00:36:23,292 - INFO - Start polling.
2025-04-06 00:36:28,424 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:36:28,424 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:37:27,011 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:38:23 MSK)" was missed by 0:00:03.720415
2025-04-06 00:38:24,460 - ERROR - Unexpected error in process_my_sets for user 1999873173: Button_data_invalid
2025-04-06 00:38:27,031 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:39:23 MSK)" was missed by 0:00:03.740306
2025-04-06 00:39:27,077 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:40:23 MSK)" was missed by 0:00:03.785626
2025-04-06 00:39:58,443 - INFO - Stop polling...
2025-04-06 00:39:58,443 - WARNING - Goodbye!
2025-04-06 00:40:16,088 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:40:16,236 - WARNING - Updates were skipped successfully.
2025-04-06 00:40:16,238 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:40:16,238 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:40:16,238 - INFO - Scheduler started
2025-04-06 00:40:16,238 - INFO - Scheduler started with optimized configuration
2025-04-06 00:40:16,238 - INFO - Бот запущен.
2025-04-06 00:40:16,238 - INFO - Start polling.
2025-04-06 00:40:19,206 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:40:19,207 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:40:31,100 - ERROR - Unexpected error in process_my_sets for user 1999873173: Button_data_invalid
2025-04-06 00:40:36,366 - INFO - Stop polling...
2025-04-06 00:40:36,367 - WARNING - Goodbye!
2025-04-06 00:47:35,806 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:47:35,964 - WARNING - Updates were skipped successfully.
2025-04-06 00:47:35,969 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:47:35,970 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:47:35,970 - INFO - Scheduler started
2025-04-06 00:47:35,970 - INFO - Scheduler started with optimized configuration
2025-04-06 00:47:35,970 - INFO - Бот запущен.
2025-04-06 00:47:35,971 - INFO - Start polling.
2025-04-06 00:47:37,898 - INFO - Stop polling...
2025-04-06 00:47:37,899 - WARNING - Goodbye!
2025-04-06 00:47:39,889 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:47:40,035 - WARNING - Updates were skipped successfully.
2025-04-06 00:47:40,037 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:47:40,037 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:47:40,037 - INFO - Scheduler started
2025-04-06 00:47:40,037 - INFO - Scheduler started with optimized configuration
2025-04-06 00:47:40,037 - INFO - Бот запущен.
2025-04-06 00:47:40,038 - INFO - Start polling.
2025-04-06 00:47:45,697 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:47:45,697 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:47:59,595 - INFO - Получен сет 'Advanced Academic Writing' из базы данных для пользователя 1999873173
2025-04-06 00:47:59,596 - INFO - Для пользователя 1999873173 с уровнем B2 выбран сет 'Advanced Academic Writing'
2025-04-06 00:47:59,596 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Academic Writing.txt
2025-04-06 00:47:59,596 - ERROR - Файл сета не найден: levels/B2/Advanced Academic Writing.txt
2025-04-06 00:48:04,401 - INFO - Проверка директории сетов для пользователя 1999873173, уровень B2, путь: levels/B2
2025-04-06 00:48:04,401 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 00:48:04,564 - ERROR - Необработанная ошибка в process_my_sets для пользователя 1999873173: Button_data_invalid
2025-04-06 00:48:06,163 - INFO - Проверка директории сетов для пользователя 1999873173, уровень B2, путь: levels/B2
2025-04-06 00:48:06,163 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 00:48:06,239 - ERROR - Необработанная ошибка в process_my_sets для пользователя 1999873173: Button_data_invalid
2025-04-06 00:48:43,813 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:49:40 MSK)" was missed by 0:00:03.776445
2025-04-06 00:49:43,802 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:50:40 MSK)" was missed by 0:00:03.765252
2025-04-06 00:50:23,576 - INFO - Stop polling...
2025-04-06 00:50:23,576 - WARNING - Goodbye!
2025-04-06 00:56:49,700 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:56:49,854 - WARNING - Updates were skipped successfully.
2025-04-06 00:56:49,859 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:56:49,859 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:56:49,859 - INFO - Scheduler started
2025-04-06 00:56:49,860 - INFO - Scheduler started with optimized configuration
2025-04-06 00:56:49,860 - INFO - Бот запущен.
2025-04-06 00:56:49,860 - INFO - Start polling.
2025-04-06 00:56:54,815 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 00:56:54,816 - INFO - Пользователь 1999873173 уже существует
2025-04-06 00:57:00,788 - INFO - Проверка директории сетов для пользователя 1999873173, уровень B2, путь: levels/B2
2025-04-06 00:57:00,789 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 00:57:04,147 - INFO - Проверка директории сетов для пользователя 1999873173, уровень B2, путь: levels/B2
2025-04-06 00:57:04,148 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 00:57:05,372 - INFO - Cleared learned words for user 1999873173
2025-04-06 00:57:15,813 - INFO - Получен сет 'Science & Innovation' из базы данных для пользователя 1999873173
2025-04-06 00:57:15,813 - INFO - Для пользователя 1999873173 с уровнем B2 выбран сет 'Science & Innovation'
2025-04-06 00:57:15,813 - INFO - Проверка пути к файлу сета: levels/B2/Science & Innovation.txt
2025-04-06 00:57:43,360 - INFO - Получен сет 'Science & Innovation' из базы данных для пользователя 1999873173
2025-04-06 00:57:43,361 - INFO - Для пользователя 1999873173 с уровнем B2 выбран сет 'Science & Innovation'
2025-04-06 00:57:43,361 - INFO - Проверка пути к файлу сета: levels/B2/Science & Innovation.txt
2025-04-06 00:57:53,484 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 00:58:49 MSK)" was missed by 0:00:03.625900
2025-04-06 00:58:19,926 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-06 00:58:19,926 - INFO - Найдено 3 файлов сетов в директории levels/A1
2025-04-06 00:58:21,051 - INFO - Cleared learned words for user 1999873173
2025-04-06 00:58:38,019 - INFO - Cleared learned words for user 1999873173
2025-04-06 00:58:44,197 - INFO - Stop polling...
2025-04-06 00:58:44,198 - WARNING - Goodbye!
2025-04-06 00:58:51,090 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 00:58:51,257 - WARNING - Updates were skipped successfully.
2025-04-06 00:58:51,259 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 00:58:51,259 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 00:58:51,259 - INFO - Scheduler started
2025-04-06 00:58:51,259 - INFO - Scheduler started with optimized configuration
2025-04-06 00:58:51,259 - INFO - Бот запущен.
2025-04-06 00:58:51,260 - INFO - Start polling.
2025-04-06 00:58:56,704 - INFO - Получена команда /start от chat_id: 380675615
2025-04-06 00:58:56,705 - INFO - Пользователь 380675615 уже существует
2025-04-06 00:58:58,471 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'reset_daily_words_cache' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/words.py", line 47, in send_words_day_schedule
    reset_daily_words_cache(chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'reset_daily_words_cache' is not defined
2025-04-06 00:59:08,461 - INFO - Получена команда /start от chat_id: 380675615
2025-04-06 00:59:08,461 - INFO - Пользователь 380675615 уже существует
2025-04-06 00:59:10,581 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:59:10,581 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:59:45,625 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 00:59:45,625 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 00:59:47,230 - INFO - Resetting daily words cache for user 380675615
2025-04-06 00:59:47,231 - INFO - Cache successfully reset for user 380675615
2025-04-06 00:59:47,231 - INFO - Cleared learned words for user 380675615
2025-04-06 00:59:54,878 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:00:51 MSK)" was missed by 0:00:03.619596
2025-04-06 00:59:56,477 - INFO - У пользователя 380675615 есть 0 выученных слов
2025-04-06 00:59:56,479 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:59:56,480 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 00:59:56,481 - INFO - Пользователь 380675615 в режиме повторения: False
2025-04-06 00:59:56,481 - INFO - Подготовлено 5 слов для квиза пользователя 380675615
2025-04-06 01:00:26,996 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:00:26,996 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:00:27,344 - INFO - Stop polling...
2025-04-06 01:00:27,344 - WARNING - Goodbye!
2025-04-06 01:05:53,689 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 01:05:53,847 - WARNING - Updates were skipped successfully.
2025-04-06 01:05:53,849 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 01:05:53,849 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 01:05:53,849 - INFO - Scheduler started
2025-04-06 01:05:53,849 - INFO - Scheduler started with optimized configuration
2025-04-06 01:05:53,849 - INFO - Бот запущен.
2025-04-06 01:05:53,849 - INFO - Start polling.
2025-04-06 01:06:05,041 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 01:06:05,041 - INFO - Пользователь 1999873173 уже существует
2025-04-06 01:06:57,605 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:07:53 MSK)" was missed by 0:00:03.756164
2025-04-06 01:07:57,768 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:08:53 MSK)" was missed by 0:00:03.919878
2025-04-06 01:08:57,757 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:09:53 MSK)" was missed by 0:00:03.908266
2025-04-06 01:09:55,824 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:10:53 MSK)" was missed by 0:00:01.975118
2025-04-06 01:10:57,770 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:11:53 MSK)" was missed by 0:00:03.921625
2025-04-06 01:11:56,355 - INFO - Stop polling...
2025-04-06 01:11:56,356 - WARNING - Goodbye!
2025-04-06 01:11:58,287 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 01:11:58,446 - WARNING - Updates were skipped successfully.
2025-04-06 01:11:58,450 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 01:11:58,451 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 01:11:58,451 - INFO - Scheduler started
2025-04-06 01:11:58,451 - INFO - Scheduler started with optimized configuration
2025-04-06 01:11:58,451 - INFO - Бот запущен.
2025-04-06 01:11:58,452 - INFO - Start polling.
2025-04-06 01:12:01,999 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:12:01,999 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:12:06,330 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-06 01:12:06,330 - INFO - Найдено 3 файлов сетов в директории levels/A1
2025-04-06 01:12:09,539 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 01:12:09,539 - INFO - Cache successfully reset for user 1999873173
2025-04-06 01:12:09,539 - INFO - Cleared learned words for user 1999873173
2025-04-06 01:12:15,599 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:12:15,599 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:12:21,288 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 01:12:21,288 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 01:12:21,288 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-06 01:12:31,662 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-06 01:12:31,662 - INFO - Найдено 3 файлов сетов в директории levels/A1
2025-04-06 01:12:35,233 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-06 01:12:35,233 - INFO - Найдено 3 файлов сетов в директории levels/A1
2025-04-06 01:12:42,347 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-06 01:12:42,347 - INFO - Найдено 3 файлов сетов в директории levels/A1
2025-04-06 01:12:45,975 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 01:12:45,975 - INFO - Cache successfully reset for user 1999873173
2025-04-06 01:12:46,981 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:12:46,981 - INFO - Найдено 3 файлов сетов в директории levels/C1
2025-04-06 01:12:50,588 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:12:50,588 - INFO - Найдено 3 файлов сетов в директории levels/C1
2025-04-06 01:12:52,335 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:12:52,335 - INFO - Найдено 3 файлов сетов в директории levels/C1
2025-04-06 01:12:56,832 - INFO - Cleared learned words for user 1999873173
2025-04-06 01:13:02,312 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:13:58 MSK)" was missed by 0:00:03.862184
2025-04-06 01:13:18,318 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:13:18,319 - INFO - Найдено 3 файлов сетов в директории levels/C1
2025-04-06 01:13:20,846 - INFO - Cleared learned words for user 1999873173
2025-04-06 01:13:26,543 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:13:26,543 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:14:00,357 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:14:58 MSK)" was missed by 0:00:01.907752
2025-04-06 01:15:02,200 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:15:58 MSK)" was missed by 0:00:03.750606
2025-04-06 01:16:02,131 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:16:58 MSK)" was missed by 0:00:03.681521
2025-04-06 01:17:02,061 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:17:58 MSK)" was missed by 0:00:03.611416
2025-04-06 01:18:01,992 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:18:58 MSK)" was missed by 0:00:03.542231
2025-04-06 01:19:00,257 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:19:58 MSK)" was missed by 0:00:01.807639
2025-04-06 01:20:01,927 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:20:58 MSK)" was missed by 0:00:03.477150
2025-04-06 01:20:27,463 - INFO - Получена команда /start от chat_id: 380675615
2025-04-06 01:20:27,463 - INFO - Пользователь 380675615 уже существует
2025-04-06 01:20:28,823 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:20:28,824 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:20:39,046 - INFO - У пользователя 380675615 есть 4 выученных слов
2025-04-06 01:20:39,046 - INFO - Пользователь 380675615 в режиме повторения: False
2025-04-06 01:20:39,046 - INFO - Подготовлено 5 слов для квиза пользователя 380675615
2025-04-06 01:20:55,212 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:20:55,212 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:21:01,180 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:21:01,180 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:21:01,919 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:21:58 MSK)" was missed by 0:00:03.469003
2025-04-06 01:21:19,474 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:21:19,475 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:21:32,012 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:21:32,013 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:21:45,610 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:21:45,610 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:21:48,699 - INFO - Cleared learned words for user 380675615
2025-04-06 01:21:48,699 - INFO - Resetting daily words cache for user 380675615
2025-04-06 01:21:48,699 - INFO - Cache successfully reset for user 380675615
2025-04-06 01:21:59,896 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:21:59,896 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:22:01,684 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:22:58 MSK)" was missed by 0:00:03.234397
2025-04-06 01:22:06,816 - INFO - Проверка директории сетов для пользователя 380675615, уровень B2, путь: levels/B2
2025-04-06 01:22:06,816 - INFO - Найдено 3 файлов сетов в директории levels/B2
2025-04-06 01:22:09,089 - INFO - Resetting daily words cache for user 380675615
2025-04-06 01:22:09,089 - INFO - Cache successfully reset for user 380675615
2025-04-06 01:22:09,089 - INFO - Cleared learned words for user 380675615
2025-04-06 01:22:15,177 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:22:15,177 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:22:21,381 - INFO - У пользователя 380675615 есть 0 выученных слов
2025-04-06 01:22:21,382 - INFO - Пользователь 380675615 в режиме повторения: False
2025-04-06 01:22:21,382 - INFO - Подготовлено 5 слов для квиза пользователя 380675615
2025-04-06 01:22:55,133 - INFO - Получен сет 'Advanced Travel Vocabulary' из базы данных для пользователя 380675615
2025-04-06 01:22:55,133 - INFO - Для пользователя 380675615 с уровнем B2 выбран сет 'Advanced Travel Vocabulary'
2025-04-06 01:22:55,133 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Travel Vocabulary.txt
2025-04-06 01:23:00,084 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:23:58 MSK)" was missed by 0:00:01.634109
2025-04-06 01:23:22,552 - INFO - Получен сет 'Advanced Travel Vocabulary' из базы данных для пользователя 380675615
2025-04-06 01:23:22,552 - INFO - Для пользователя 380675615 с уровнем B2 выбран сет 'Advanced Travel Vocabulary'
2025-04-06 01:23:22,552 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Travel Vocabulary.txt
2025-04-06 01:24:01,707 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:24:58 MSK)" was missed by 0:00:03.257621
2025-04-06 01:24:05,575 - INFO - Получен сет 'Advanced Travel Vocabulary' из базы данных для пользователя 380675615
2025-04-06 01:24:05,575 - INFO - Для пользователя 380675615 с уровнем B2 выбран сет 'Advanced Travel Vocabulary'
2025-04-06 01:24:05,575 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Travel Vocabulary.txt
2025-04-06 01:24:12,056 - INFO - Получен сет 'Advanced Travel Vocabulary' из базы данных для пользователя 380675615
2025-04-06 01:24:12,057 - INFO - Для пользователя 380675615 с уровнем B2 выбран сет 'Advanced Travel Vocabulary'
2025-04-06 01:24:12,057 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Travel Vocabulary.txt
2025-04-06 01:24:25,664 - ERROR - Error updating test_words_count for user 380675615: no such column: test_words_count
2025-04-06 01:24:25,664 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-640' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: test_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 252, in process_learning_settings_input
    crud.update_user_test_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 203, in update_user_test_words_count
    cursor.execute("UPDATE users SET test_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: test_words_count
2025-04-06 01:24:37,724 - INFO - Получен сет 'Advanced Travel Vocabulary' из базы данных для пользователя 380675615
2025-04-06 01:24:37,724 - INFO - Для пользователя 380675615 с уровнем B2 выбран сет 'Advanced Travel Vocabulary'
2025-04-06 01:24:37,724 - INFO - Проверка пути к файлу сета: levels/B2/Advanced Travel Vocabulary.txt
2025-04-06 01:25:01,730 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:25:58 MSK)" was missed by 0:00:03.280411
2025-04-06 01:25:49,428 - INFO - Stop polling...
2025-04-06 01:25:49,429 - WARNING - Goodbye!
2025-04-06 01:28:37,780 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 01:28:37,940 - WARNING - Updates were skipped successfully.
2025-04-06 01:28:37,945 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 01:28:37,946 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 01:28:37,946 - INFO - Scheduler started
2025-04-06 01:28:37,946 - INFO - Scheduler started with optimized configuration
2025-04-06 01:28:37,946 - INFO - Бот запущен.
2025-04-06 01:28:37,946 - INFO - Start polling.
2025-04-06 01:28:49,465 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 01:28:49,465 - INFO - Пользователь 1999873173 уже существует
2025-04-06 01:28:52,196 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:28:52,196 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:29:41,905 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:30:37 MSK)" was missed by 0:00:03.960389
2025-04-06 01:30:41,839 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:31:37 MSK)" was missed by 0:00:03.893917
2025-04-06 01:30:54,230 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-06 01:30:54,230 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-06 01:30:54,230 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-06 01:31:05,388 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:31:05,388 - INFO - Найдено 3 файлов сетов в директории levels/C1
2025-04-06 01:31:15,767 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-121' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 275, in handle_dictionary_test
    await callback.message.edit_text(
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-04-06 01:31:41,807 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:32:37 MSK)" was missed by 0:00:03.862670
2025-04-06 01:32:39,858 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:33:37 MSK)" was missed by 0:00:01.913395
2025-04-06 01:33:41,568 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:34:37 MSK)" was missed by 0:00:03.622748
2025-04-06 01:34:41,537 - WARNING - Run time of job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-06 01:35:37 MSK)" was missed by 0:00:03.592423
2025-04-06 01:35:20,973 - INFO - Stop polling...
2025-04-06 01:35:20,974 - WARNING - Goodbye!
2025-04-06 01:35:21,955 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-06 01:35:22,114 - WARNING - Updates were skipped successfully.
2025-04-06 01:35:22,116 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-06 01:35:22,116 - INFO - Added job "scheduler_job" to job store "default"
2025-04-06 01:35:22,116 - INFO - Scheduler started
2025-04-06 01:35:22,116 - INFO - Scheduler started with optimized configuration
2025-04-06 01:35:22,116 - INFO - Бот запущен.
2025-04-06 01:35:22,116 - INFO - Start polling.
2025-04-06 01:35:25,471 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-06 01:35:25,471 - INFO - Пользователь 1999873173 уже существует
2025-04-06 01:35:29,287 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:35:29,287 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:35:32,756 - INFO - Проверка директории сетов для пользователя 1999873173, уровень C1, путь: levels/C1
2025-04-06 01:35:32,757 - INFO - Найдено 22 файлов сетов в директории levels/C1
2025-04-06 01:35:39,059 - INFO - Resetting daily words cache for user 1999873173
2025-04-06 01:35:39,059 - INFO - Cache successfully reset for user 1999873173
2025-04-06 01:35:39,059 - INFO - Cleared learned words for user 1999873173
2025-04-06 01:35:42,632 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:35:42,633 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-06 01:35:47,773 - INFO - Stop polling...
2025-04-06 01:35:47,773 - WARNING - Goodbye!
2025-04-10 00:21:09,708 - INFO - Bot: HabitTrackerBot [@AllHabitsTrackerBot]
2025-04-10 00:21:09,887 - WARNING - Updates were skipped successfully.
2025-04-10 00:21:09,892 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:21:09,893 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:21:09,893 - INFO - Scheduler started
2025-04-10 00:21:09,893 - INFO - Scheduler started with optimized configuration
2025-04-10 00:21:09,893 - INFO - Бот запущен.
2025-04-10 00:21:09,893 - INFO - Start polling.
2025-04-10 00:21:15,175 - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-04-10 00:21:16,814 - INFO - Stop polling...
2025-04-10 00:21:16,814 - WARNING - Goodbye!
2025-04-10 00:21:57,332 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:21:57,494 - WARNING - Updates were skipped successfully.
2025-04-10 00:21:57,496 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:21:57,497 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:21:57,497 - INFO - Scheduler started
2025-04-10 00:21:57,497 - INFO - Scheduler started with optimized configuration
2025-04-10 00:21:57,497 - INFO - Бот запущен.
2025-04-10 00:21:57,497 - INFO - Start polling.
2025-04-10 00:22:01,145 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:22:01,145 - INFO - Пользователь 1999873173 уже существует
2025-04-10 00:22:03,949 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:03,950 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:17,846 - INFO - Получен сет 'Advanced Collocations & Phrases' из базы данных для пользователя 1999873173
2025-04-10 00:22:17,846 - INFO - Проверка пути к файлу сета: levels/C1/Advanced Collocations & Phrases.txt
2025-04-10 00:22:27,352 - INFO - Resetting daily words cache for user 1999873173
2025-04-10 00:22:27,352 - INFO - Cache successfully reset for user 1999873173
2025-04-10 00:22:28,543 - INFO - Проверка директории сетов для пользователя 1999873173, уровень A1, путь: levels/A1
2025-04-10 00:22:28,544 - INFO - Найдено 14 файлов сетов в директории levels/A1
2025-04-10 00:22:32,095 - INFO - Cleared learned words for user 1999873173
2025-04-10 00:22:40,796 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 00:22:40,797 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 00:22:57,500 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:23:57 MSK)" (scheduled at 2025-04-10 00:22:57.496578+03:00)
2025-04-10 00:22:57,506 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:57,506 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:57,507 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:57,507 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:22:57,533 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:23:57 MSK)" executed successfully
2025-04-10 00:22:59,477 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-10 00:22:59,477 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-10 00:22:59,477 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-10 00:23:46,738 - ERROR - Error updating memorize_words_count for user 1999873173: no such column: memorize_words_count
2025-04-10 00:23:46,738 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-224' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: memorize_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 287, in process_learning_settings_input
    crud.update_user_memorize_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 213, in update_user_memorize_words_count
    cursor.execute("UPDATE users SET memorize_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: memorize_words_count
2025-04-10 00:23:55,257 - ERROR - Error updating test_words_count for user 1999873173: no such column: test_words_count
2025-04-10 00:23:55,258 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-237' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: test_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 281, in process_learning_settings_input
    crud.update_user_test_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 203, in update_user_test_words_count
    cursor.execute("UPDATE users SET test_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: test_words_count
2025-04-10 00:23:57,501 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:24:57 MSK)" (scheduled at 2025-04-10 00:23:57.496578+03:00)
2025-04-10 00:23:57,502 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:24:57 MSK)" executed successfully
2025-04-10 00:24:00,195 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 00:24:00,195 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 00:24:36,213 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 00:24:36,213 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 00:24:40,388 - INFO - Stop polling...
2025-04-10 00:24:40,389 - WARNING - Goodbye!
2025-04-10 00:30:23,771 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:30:23,941 - WARNING - Updates were skipped successfully.
2025-04-10 00:30:23,955 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:30:23,960 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:30:23,960 - INFO - Scheduler started
2025-04-10 00:30:23,960 - INFO - Scheduler started with optimized configuration
2025-04-10 00:30:23,961 - INFO - Бот запущен.
2025-04-10 00:30:23,961 - INFO - Start polling.
2025-04-10 00:30:27,455 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:30:27,455 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:30:42,935 - ERROR - Error updating test_words_count for user 1999873173: no such column: test_words_count
2025-04-10 00:30:42,935 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-55' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: test_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 282, in process_learning_settings_input
    crud.update_user_test_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 203, in update_user_test_words_count
    cursor.execute("UPDATE users SET test_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: test_words_count
2025-04-10 00:30:52,823 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 00:30:52,823 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 00:31:05,308 - ERROR - Error updating test_words_count for user 1999873173: no such column: test_words_count
2025-04-10 00:31:05,308 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-93' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: test_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 282, in process_learning_settings_input
    crud.update_user_test_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 203, in update_user_test_words_count
    cursor.execute("UPDATE users SET test_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: test_words_count
2025-04-10 00:31:08,168 - INFO - Stop polling...
2025-04-10 00:31:08,168 - WARNING - Goodbye!
2025-04-10 00:31:38,457 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:31:38,625 - WARNING - Updates were skipped successfully.
2025-04-10 00:31:38,626 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:31:38,626 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:31:38,626 - INFO - Scheduler started
2025-04-10 00:31:38,626 - INFO - Scheduler started with optimized configuration
2025-04-10 00:31:38,626 - INFO - Бот запущен.
2025-04-10 00:31:38,627 - INFO - Start polling.
2025-04-10 00:32:13,029 - ERROR - Error updating test_words_count for user 1999873173: no such column: test_words_count
2025-04-10 00:32:13,029 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-21' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: test_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 282, in process_learning_settings_input
    crud.update_user_test_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 203, in update_user_test_words_count
    cursor.execute("UPDATE users SET test_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: test_words_count
2025-04-10 00:32:38,633 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:33:38 MSK)" (scheduled at 2025-04-10 00:32:38.626415+03:00)
2025-04-10 00:32:38,639 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:32:38,640 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:32:38,642 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:32:38,642 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:32:38,664 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:33:38 MSK)" executed successfully
2025-04-10 00:33:01,986 - ERROR - Error updating memorize_words_count for user 1999873173: no such column: memorize_words_count
2025-04-10 00:33:01,987 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-36' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such column: memorize_words_count')>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 288, in process_learning_settings_input
    crud.update_user_memorize_words_count(chat_id, value)
  File "/home/andrii/telegram-bot/english_learning_bot/database/crud.py", line 213, in update_user_memorize_words_count
    cursor.execute("UPDATE users SET memorize_words_count = ? WHERE chat_id = ?", (count, chat_id))
sqlite3.OperationalError: no such column: memorize_words_count
2025-04-10 00:33:38,631 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:34:38 MSK)" (scheduled at 2025-04-10 00:33:38.626415+03:00)
2025-04-10 00:33:38,634 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:34:38 MSK)" executed successfully
2025-04-10 00:34:19,031 - INFO - Stop polling...
2025-04-10 00:34:19,032 - WARNING - Goodbye!
2025-04-10 00:36:39,248 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:36:39,434 - WARNING - Updates were skipped successfully.
2025-04-10 00:36:39,440 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:36:39,441 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:36:39,441 - INFO - Scheduler started
2025-04-10 00:36:39,441 - INFO - Scheduler started with optimized configuration
2025-04-10 00:36:39,441 - INFO - Бот запущен.
2025-04-10 00:36:39,442 - INFO - Start polling.
2025-04-10 00:36:45,049 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:36:45,049 - INFO - Пользователь 1999873173 уже существует
2025-04-10 00:36:46,827 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:36:46,828 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:36:48,564 - INFO - У пользователя 1999873173 есть 3 выученных слов
2025-04-10 00:36:48,564 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-10 00:36:48,565 - INFO - Подготовлено 10 слов для квиза пользователя 1999873173
2025-04-10 00:37:24,290 - INFO - Stop polling...
2025-04-10 00:37:24,291 - WARNING - Goodbye!
2025-04-10 00:37:31,715 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:37:31,885 - WARNING - Updates were skipped successfully.
2025-04-10 00:37:31,888 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:37:31,889 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:37:31,889 - INFO - Scheduler started
2025-04-10 00:37:31,889 - INFO - Scheduler started with optimized configuration
2025-04-10 00:37:31,889 - INFO - Бот запущен.
2025-04-10 00:37:31,890 - INFO - Start polling.
2025-04-10 00:37:34,840 - INFO - Stop polling...
2025-04-10 00:37:34,841 - WARNING - Goodbye!
2025-04-10 00:38:26,529 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:38:26,712 - WARNING - Updates were skipped successfully.
2025-04-10 00:38:26,718 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:38:26,719 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:38:26,719 - INFO - Scheduler started
2025-04-10 00:38:26,719 - INFO - Scheduler started with optimized configuration
2025-04-10 00:38:26,719 - INFO - Бот запущен.
2025-04-10 00:38:26,719 - INFO - Start polling.
2025-04-10 00:38:30,495 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:38:30,504 - INFO - Added new user with chat_id: 1999873173 with default set: A1 Basic 1
2025-04-10 00:38:30,504 - INFO - Добавлен новый пользователь с chat_id 1999873173
2025-04-10 00:38:30,504 - INFO - Установлен базовый сет A1 Basic 1 для нового пользователя 1999873173
2025-04-10 00:39:26,730 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:40:26 MSK)" (scheduled at 2025-04-10 00:39:26.717577+03:00)
2025-04-10 00:39:26,731 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:39:26,731 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:39:26,733 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:39:26,733 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:39:26,763 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:40:26 MSK)" executed successfully
2025-04-10 00:40:26,731 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:41:26 MSK)" (scheduled at 2025-04-10 00:40:26.717577+03:00)
2025-04-10 00:40:26,734 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:41:26 MSK)" executed successfully
2025-04-10 00:41:26,729 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:42:26 MSK)" (scheduled at 2025-04-10 00:41:26.717577+03:00)
2025-04-10 00:41:26,730 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:42:26 MSK)" executed successfully
2025-04-10 00:42:19,274 - INFO - Stop polling...
2025-04-10 00:42:19,276 - WARNING - Goodbye!
2025-04-10 00:42:20,675 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:42:20,841 - WARNING - Updates were skipped successfully.
2025-04-10 00:42:20,842 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:42:20,842 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:42:20,842 - INFO - Scheduler started
2025-04-10 00:42:20,842 - INFO - Scheduler started with optimized configuration
2025-04-10 00:42:20,842 - INFO - Бот запущен.
2025-04-10 00:42:20,843 - INFO - Start polling.
2025-04-10 00:42:27,582 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:42:27,583 - INFO - Пользователь 1999873173 уже существует
2025-04-10 00:42:33,658 - INFO - Получен ввод настройки test_words от пользователя 1999873173: 2
2025-04-10 00:42:33,659 - INFO - Updated test_words_count to 2 for user 1999873173
2025-04-10 00:42:33,659 - INFO - Обновлено количество слов для теста у пользователя 1999873173: 2
2025-04-10 00:42:33,659 - INFO - Проверка обновления: было 5, стало 5
2025-04-10 00:43:20,849 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:44:20 MSK)" (scheduled at 2025-04-10 00:43:20.842439+03:00)
2025-04-10 00:43:20,850 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:43:20,850 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:43:20,851 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:43:20,851 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:43:20,871 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:44:20 MSK)" executed successfully
2025-04-10 00:44:20,851 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:45:20 MSK)" (scheduled at 2025-04-10 00:44:20.842439+03:00)
2025-04-10 00:44:20,853 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:45:20 MSK)" executed successfully
2025-04-10 00:45:20,849 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:46:20 MSK)" (scheduled at 2025-04-10 00:45:20.842439+03:00)
2025-04-10 00:45:20,851 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:46:20 MSK)" executed successfully
2025-04-10 00:46:20,847 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:47:20 MSK)" (scheduled at 2025-04-10 00:46:20.842439+03:00)
2025-04-10 00:46:20,849 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:47:20 MSK)" executed successfully
2025-04-10 00:46:32,840 - INFO - Stop polling...
2025-04-10 00:46:32,842 - WARNING - Goodbye!
2025-04-10 00:50:19,146 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:50:19,321 - WARNING - Updates were skipped successfully.
2025-04-10 00:50:19,326 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:50:19,327 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:50:19,327 - INFO - Scheduler started
2025-04-10 00:50:19,327 - INFO - Scheduler started with optimized configuration
2025-04-10 00:50:19,327 - INFO - Бот запущен.
2025-04-10 00:50:19,328 - INFO - Start polling.
2025-04-10 00:50:21,923 - INFO - Stop polling...
2025-04-10 00:50:21,924 - WARNING - Goodbye!
2025-04-10 00:50:24,969 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:50:25,140 - WARNING - Updates were skipped successfully.
2025-04-10 00:50:25,143 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:50:25,143 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:50:25,143 - INFO - Scheduler started
2025-04-10 00:50:25,144 - INFO - Scheduler started with optimized configuration
2025-04-10 00:50:25,144 - INFO - Бот запущен.
2025-04-10 00:50:25,144 - INFO - Start polling.
2025-04-10 00:50:29,505 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 68, in handle_test_settings
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:50:31,800 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:50:39,351 - INFO - Stop polling...
2025-04-10 00:50:39,352 - WARNING - Goodbye!
2025-04-10 00:50:40,886 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:50:41,063 - WARNING - Updates were skipped successfully.
2025-04-10 00:50:41,065 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:50:41,065 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:50:41,066 - INFO - Scheduler started
2025-04-10 00:50:41,066 - INFO - Scheduler started with optimized configuration
2025-04-10 00:50:41,066 - INFO - Бот запущен.
2025-04-10 00:50:41,066 - INFO - Start polling.
2025-04-10 00:50:46,481 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:50:46,481 - INFO - Пользователь 1999873173 уже существует
2025-04-10 00:50:50,253 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:51:00,017 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:51:05,154 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-31' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:51:10,418 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-44' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:51:12,293 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:51:12,293 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:51:15,732 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-67' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:51:20,951 - INFO - Stop polling...
2025-04-10 00:51:20,952 - WARNING - Goodbye!
2025-04-10 00:51:22,829 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:51:23,011 - WARNING - Updates were skipped successfully.
2025-04-10 00:51:23,013 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:51:23,013 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:51:23,013 - INFO - Scheduler started
2025-04-10 00:51:23,013 - INFO - Scheduler started with optimized configuration
2025-04-10 00:51:23,013 - INFO - Бот запущен.
2025-04-10 00:51:23,014 - INFO - Start polling.
2025-04-10 00:51:41,972 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:52:23,016 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:53:23 MSK)" (scheduled at 2025-04-10 00:52:23.013005+03:00)
2025-04-10 00:52:23,018 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:52:23,019 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:52:23,023 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:52:23,023 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:52:23,047 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:53:23 MSK)" executed successfully
2025-04-10 00:53:23,016 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:54:23 MSK)" (scheduled at 2025-04-10 00:53:23.013005+03:00)
2025-04-10 00:53:23,018 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 00:54:23 MSK)" executed successfully
2025-04-10 00:53:33,705 - INFO - Stop polling...
2025-04-10 00:53:33,706 - WARNING - Goodbye!
2025-04-10 00:53:35,870 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:53:36,033 - WARNING - Updates were skipped successfully.
2025-04-10 00:53:36,037 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:53:36,038 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:53:36,038 - INFO - Scheduler started
2025-04-10 00:53:36,038 - INFO - Scheduler started with optimized configuration
2025-04-10 00:53:36,038 - INFO - Бот запущен.
2025-04-10 00:53:36,038 - INFO - Start polling.
2025-04-10 00:53:40,129 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=NameError("name 'ensure_learning_columns_exist' is not defined")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/english_learning_bot/handlers/learning.py", line 51, in handle_learning_menu
    ensure_learning_columns_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'ensure_learning_columns_exist' is not defined
2025-04-10 00:53:43,479 - INFO - Stop polling...
2025-04-10 00:53:43,479 - WARNING - Goodbye!
2025-04-10 00:54:12,546 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:54:12,709 - WARNING - Updates were skipped successfully.
2025-04-10 00:54:12,711 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:54:12,712 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:54:12,712 - INFO - Scheduler started
2025-04-10 00:54:12,712 - INFO - Scheduler started with optimized configuration
2025-04-10 00:54:12,712 - INFO - Бот запущен.
2025-04-10 00:54:12,713 - INFO - Start polling.
2025-04-10 00:54:17,827 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:54:17,827 - INFO - Пользователь 1999873173 уже существует
2025-04-10 00:54:28,970 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-10 00:54:28,970 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:54:28,970 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:54:28,971 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-10 00:54:28,972 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-10 00:54:58,909 - ERROR - Ошибка при обработке настроек: 'Bot' object has no attribute 'get_chat_history'
2025-04-10 00:55:08,020 - INFO - Stop polling...
2025-04-10 00:55:08,020 - WARNING - Goodbye!
2025-04-10 00:55:15,403 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 00:55:15,572 - WARNING - Updates were skipped successfully.
2025-04-10 00:55:15,575 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 00:55:15,575 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 00:55:15,575 - INFO - Scheduler started
2025-04-10 00:55:15,575 - INFO - Scheduler started with optimized configuration
2025-04-10 00:55:15,575 - INFO - Бот запущен.
2025-04-10 00:55:15,576 - INFO - Start polling.
2025-04-10 00:55:19,204 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 00:55:19,228 - INFO - Added new user with chat_id: 1999873173 with default set: A1 Basic 1
2025-04-10 00:55:19,229 - INFO - Добавлен новый пользователь с chat_id 1999873173
2025-04-10 00:55:19,229 - INFO - Установлен базовый сет A1 Basic 1 для нового пользователя 1999873173
2025-04-10 00:55:24,641 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:55:24,642 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 00:55:27,171 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-10 00:55:27,172 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-10 00:55:27,172 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-10 00:55:53,654 - ERROR - Ошибка при обработке настроек: 'Bot' object has no attribute 'get_chat_history'
2025-04-10 00:56:02,746 - INFO - Stop polling...
2025-04-10 00:56:02,746 - WARNING - Goodbye!
2025-04-10 01:04:12,602 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:04:12,771 - WARNING - Updates were skipped successfully.
2025-04-10 01:04:12,776 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:04:12,777 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:04:12,777 - INFO - Scheduler started
2025-04-10 01:04:12,777 - INFO - Scheduler started with optimized configuration
2025-04-10 01:04:12,777 - INFO - Бот запущен.
2025-04-10 01:04:12,778 - INFO - Start polling.
2025-04-10 01:04:18,965 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:04:18,966 - INFO - Пользователь 1999873173 уже существует
2025-04-10 01:04:36,237 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-64' coro=<Dispatcher._process_polling_updates() done, defined at /home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("process_learning_settings_input() missing 1 required positional argument: 'bot'")>
Traceback (most recent call last):
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrii/telegram-bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: process_learning_settings_input() missing 1 required positional argument: 'bot'
2025-04-10 01:05:12,789 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:06:12 MSK)" (scheduled at 2025-04-10 01:05:12.775867+03:00)
2025-04-10 01:05:12,790 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:05:12,790 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:05:12,791 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:05:12,791 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:05:12,812 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:06:12 MSK)" executed successfully
2025-04-10 01:06:12,777 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:07:12 MSK)" (scheduled at 2025-04-10 01:06:12.775867+03:00)
2025-04-10 01:06:12,777 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:07:12 MSK)" executed successfully
2025-04-10 01:07:12,792 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:08:12 MSK)" (scheduled at 2025-04-10 01:07:12.775867+03:00)
2025-04-10 01:07:12,793 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:08:12 MSK)" executed successfully
2025-04-10 01:08:12,793 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:09:12 MSK)" (scheduled at 2025-04-10 01:08:12.775867+03:00)
2025-04-10 01:08:12,797 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:09:12 MSK)" executed successfully
2025-04-10 01:08:14,538 - INFO - Stop polling...
2025-04-10 01:08:14,538 - WARNING - Goodbye!
2025-04-10 01:08:17,012 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:08:17,192 - WARNING - Updates were skipped successfully.
2025-04-10 01:08:17,195 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:08:17,195 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:08:17,196 - INFO - Scheduler started
2025-04-10 01:08:17,196 - INFO - Scheduler started with optimized configuration
2025-04-10 01:08:17,196 - INFO - Бот запущен.
2025-04-10 01:08:17,196 - INFO - Start polling.
2025-04-10 01:08:33,144 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:08:33,144 - INFO - Пользователь 1999873173 уже существует
2025-04-10 01:08:49,445 - INFO - Получен ввод настройки test_words от пользователя 1999873173: 2
2025-04-10 01:08:49,451 - INFO - Updated test_words_count to 2 for user 1999873173
2025-04-10 01:08:49,451 - INFO - Обновлено количество слов для теста у пользователя 1999873173: 2
2025-04-10 01:09:16,475 - INFO - Stop polling...
2025-04-10 01:09:16,476 - WARNING - Goodbye!
2025-04-10 01:09:38,632 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:09:38,800 - WARNING - Updates were skipped successfully.
2025-04-10 01:09:38,801 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:09:38,801 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:09:38,801 - INFO - Scheduler started
2025-04-10 01:09:38,801 - INFO - Scheduler started with optimized configuration
2025-04-10 01:09:38,801 - INFO - Бот запущен.
2025-04-10 01:09:38,802 - INFO - Start polling.
2025-04-10 01:09:46,763 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:09:46,772 - INFO - Added new user with chat_id: 1999873173 with default set: A1 Basic 1
2025-04-10 01:09:46,772 - INFO - Добавлен новый пользователь с chat_id 1999873173
2025-04-10 01:09:46,773 - INFO - Установлен базовый сет A1 Basic 1 для нового пользователя 1999873173
2025-04-10 01:09:48,225 - INFO - У пользователя 1999873173 есть 0 выученных слов
2025-04-10 01:09:48,225 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:09:48,225 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:09:48,227 - INFO - Пользователь 1999873173 в режиме повторения: False
2025-04-10 01:09:48,227 - INFO - Подготовлено 5 слов для квиза пользователя 1999873173
2025-04-10 01:10:14,853 - INFO - Получен ввод настройки test_words от пользователя 1999873173: 2
2025-04-10 01:10:14,854 - INFO - Updated test_words_count to 2 for user 1999873173
2025-04-10 01:10:14,855 - INFO - Обновлено количество слов для теста у пользователя 1999873173: 2
2025-04-10 01:10:17,104 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 01:10:17,104 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 01:10:30,176 - INFO - Получен ввод настройки memorize_words от пользователя 1999873173: 10
2025-04-10 01:10:30,176 - INFO - Updated memorize_words_count to 10 for user 1999873173
2025-04-10 01:10:30,176 - INFO - Обновлено количество слов для заучивания у пользователя 1999873173: 10
2025-04-10 01:10:32,357 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 01:10:32,357 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 01:10:38,813 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:11:38 MSK)" (scheduled at 2025-04-10 01:10:38.801445+03:00)
2025-04-10 01:10:38,815 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:10:38,816 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:10:38,847 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:11:38 MSK)" executed successfully
2025-04-10 01:11:38,808 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:12:38 MSK)" (scheduled at 2025-04-10 01:11:38.801445+03:00)
2025-04-10 01:11:38,810 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:12:38 MSK)" executed successfully
2025-04-10 01:11:39,787 - INFO - Stop polling...
2025-04-10 01:11:39,788 - WARNING - Goodbye!
2025-04-10 01:11:51,889 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:11:52,051 - WARNING - Updates were skipped successfully.
2025-04-10 01:11:52,053 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:11:52,057 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:11:52,057 - INFO - Scheduler started
2025-04-10 01:11:52,057 - INFO - Scheduler started with optimized configuration
2025-04-10 01:11:52,057 - INFO - Бот запущен.
2025-04-10 01:11:52,057 - INFO - Start polling.
2025-04-10 01:11:57,485 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:11:57,486 - INFO - Пользователь 1999873173 уже существует
2025-04-10 01:12:07,347 - INFO - Получен ввод настройки test_words от пользователя 1999873173: 2
2025-04-10 01:12:07,347 - INFO - Updated test_words_count to 2 for user 1999873173
2025-04-10 01:12:07,348 - INFO - Обновлено количество слов для теста у пользователя 1999873173: 2
2025-04-10 01:12:52,055 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:13:52 MSK)" (scheduled at 2025-04-10 01:12:52.053330+03:00)
2025-04-10 01:12:52,056 - ERROR - Error getting learned words for user 380675615: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:12:52,056 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:12:52,057 - ERROR - Error getting learned words for user 1999873173: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:12:52,057 - ERROR - Error getting user timezone: cannot access local variable 'crud' where it is not associated with a value
2025-04-10 01:12:52,077 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:13:52 MSK)" executed successfully
2025-04-10 01:13:52,055 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:14:52 MSK)" (scheduled at 2025-04-10 01:13:52.053330+03:00)
2025-04-10 01:13:52,056 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:14:52 MSK)" executed successfully
2025-04-10 01:14:52,054 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:15:52 MSK)" (scheduled at 2025-04-10 01:14:52.053330+03:00)
2025-04-10 01:14:52,055 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:15:52 MSK)" executed successfully
2025-04-10 01:15:52,055 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:16:52 MSK)" (scheduled at 2025-04-10 01:15:52.053330+03:00)
2025-04-10 01:15:52,056 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:16:52 MSK)" executed successfully
2025-04-10 01:16:52,058 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:17:52 MSK)" (scheduled at 2025-04-10 01:16:52.053330+03:00)
2025-04-10 01:16:52,059 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:17:52 MSK)" executed successfully
2025-04-10 01:17:52,059 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:18:52 MSK)" (scheduled at 2025-04-10 01:17:52.053330+03:00)
2025-04-10 01:17:52,061 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:18:52 MSK)" executed successfully
2025-04-10 01:18:52,058 - INFO - Running job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:19:52 MSK)" (scheduled at 2025-04-10 01:18:52.053330+03:00)
2025-04-10 01:18:52,060 - INFO - Job "scheduler_job (trigger: interval[0:01:00], next run at: 2025-04-10 01:19:52 MSK)" executed successfully
2025-04-10 01:18:59,573 - INFO - Stop polling...
2025-04-10 01:18:59,574 - WARNING - Goodbye!
2025-04-10 01:19:01,350 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:19:01,525 - WARNING - Updates were skipped successfully.
2025-04-10 01:19:01,526 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:19:01,526 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:19:01,526 - INFO - Scheduler started
2025-04-10 01:19:01,526 - INFO - Scheduler started with optimized configuration
2025-04-10 01:19:01,526 - INFO - Бот запущен.
2025-04-10 01:19:01,526 - INFO - Start polling.
2025-04-10 01:19:11,643 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:19:11,643 - INFO - Пользователь 1999873173 уже существует
2025-04-10 01:19:20,773 - INFO - Установлено ожидание ввода test_words для пользователя 1999873173
2025-04-10 01:19:23,137 - INFO - Получено сообщение от пользователя 1999873173: 3
2025-04-10 01:19:23,137 - INFO - Обработка настройки test_words для пользователя 1999873173: 3
2025-04-10 01:19:23,138 - INFO - Обновляем test_words_count на 3 для пользователя 1999873173
2025-04-10 01:19:23,145 - INFO - Updated test_words_count to 3 for user 1999873173
2025-04-10 01:19:23,145 - INFO - Значение после обновления: 5
2025-04-10 01:19:24,816 - INFO - Установлено ожидание ввода test_words для пользователя 1999873173
2025-04-10 01:19:27,648 - INFO - Установлено ожидание ввода test_words для пользователя 1999873173
2025-04-10 01:19:33,268 - INFO - Получен сет 'A1 Basic 1' из базы данных для пользователя 1999873173
2025-04-10 01:19:33,268 - INFO - Проверка пути к файлу сета: levels/A1/A1 Basic 1.txt
2025-04-10 01:19:43,600 - INFO - Stop polling...
2025-04-10 01:19:43,600 - WARNING - Goodbye!
2025-04-10 01:26:17,422 - INFO - Bot: English_trainer [@EnglishLearning_trainer_bot]
2025-04-10 01:26:17,594 - WARNING - Updates were skipped successfully.
2025-04-10 01:26:17,599 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-10 01:26:17,600 - INFO - Added job "scheduler_job" to job store "default"
2025-04-10 01:26:17,600 - INFO - Scheduler started
2025-04-10 01:26:17,600 - INFO - Scheduler started with optimized configuration
2025-04-10 01:26:17,600 - INFO - Бот запущен.
2025-04-10 01:26:17,600 - INFO - Start polling.
2025-04-10 01:26:23,313 - INFO - Получена команда /start от chat_id: 1999873173
2025-04-10 01:26:23,314 - INFO - Пользователь 1999873173 уже существует
2025-04-10 01:26:31,944 - INFO - Пользователь 1999873173 переходит в режим ввода test_words
2025-04-10 01:26:33,622 - INFO - Получен ввод настройки test_words от пользователя 1999873173: 2
2025-04-10 01:26:33,630 - INFO - Updated test_words_count to 2 for user 1999873173
2025-04-10 01:26:33,631 - INFO - Обновлено количество слов для теста у пользователя 1999873173: 2
2025-04-10 01:26:35,639 - INFO - Пользователь 1999873173 переходит в режим ввода test_words
2025-04-10 01:26:40,449 - INFO - Stop polling...
2025-04-10 01:26:40,449 - WARNING - Goodbye!
