2025-05-15 14:09:48,838 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-15 14:09:48,845 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-15 14:09:48,846 - INFO - __main__ - Бот успешно запущен.
2025-05-15 14:10:48,728 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:11:48,665 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:12:48,665 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:13:48,673 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:14:48,674 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:15:48,672 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:16:48,660 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:17:48,665 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:18:48,665 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:19:48,663 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:20:48,663 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:21:48,663 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:22:48,662 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:23:48,661 - ERROR - services.scheduler - Error saving scheduler run time: cannot import name 'save_last_run_time' from 'bot' (/home/olegb/project/english_learning_bot/bot.py)
2025-05-15 14:24:32,257 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-15 14:24:32,381 - INFO - __main__ - Восстановлено 1 уведомлений
2025-05-15 14:24:32,382 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:16:01,041 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:16:01,053 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:16:01,054 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:18:44,472 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:18:44,473 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:18:44,477 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:18:50,452 - WARNING - utils.helpers - Сет 'C2 Basic 1' не существует для уровня C2 или не соответствует уровню. Путь: levels/C2/C2 Basic 1.txt
2025-05-27 17:18:50,452 - ERROR - utils.helpers - Базовый сет 'C2 Basic 1' не существует для уровня C2. Путь: levels/C2/C2 Basic 1.txt
2025-05-27 17:19:47,354 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:19:47,354 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:19:47,354 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:21:25,483 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:21:25,491 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:21:25,492 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:34:43,776 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:34:43,777 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:34:43,786 - INFO - __main__ - Бот успешно запущен.
2025-05-27 17:59:00,551 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 17:59:00,552 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 17:59:00,553 - INFO - __main__ - Бот успешно запущен.
2025-05-27 18:01:24,690 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-181' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest('Message_too_long')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 140, in send_words_day_schedule
    await _send_daily_words(cb, chat_id, user[1], words, reps)
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 125, in _send_daily_words
    await cb.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Message_too_long
2025-05-27 18:01:35,046 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-194' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest('Message_too_long')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 140, in send_words_day_schedule
    await _send_daily_words(cb, chat_id, user[1], words, reps)
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 125, in _send_daily_words
    await cb.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Message_too_long
2025-05-27 18:04:45,286 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-210' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest('Message_too_long')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 140, in send_words_day_schedule
    await _send_daily_words(cb, chat_id, user[1], words, reps)
  File "/home/olegb/project/english_learning_bot/handlers/words.py", line 125, in _send_daily_words
    await cb.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Message_too_long
2025-05-27 18:06:31,864 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 18:06:31,864 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 18:06:31,865 - INFO - __main__ - Бот успешно запущен.
2025-05-27 18:19:19,188 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-27 18:19:19,189 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-27 18:19:19,189 - INFO - __main__ - Бот успешно запущен.
2025-05-28 10:43:32,954 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 10:43:33,092 - INFO - __main__ - Восстановлено 5 уведомлений
2025-05-28 10:43:33,093 - INFO - __main__ - Бот успешно запущен.
2025-05-28 10:43:43,450 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 62, in process_help_about_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:43:57,880 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-42' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 121, in process_help_tips_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:43:59,945 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-51' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 92, in process_help_commands_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:44:02,466 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-60' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 62, in process_help_about_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:44:04,279 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-69' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 121, in process_help_tips_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:44:08,987 - ERROR - asyncio - Task exception was never retrieved
future: <Task finished name='Task-78' coro=<Dispatcher._process_polling_updates() done, defined at /home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/english_learning_bot/handlers/help.py", line 142, in process_help_feedback_callback
    await callback.message.edit_text(
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/types/message.py", line 2919, in edit_text
    return await self.bot.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 3122, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-05-28 10:51:32,737 - WARNING - utils.helpers - Сет 'The Natural World' не существует для уровня C1 или не соответствует уровню. Путь: levels/C1/The Natural World.txt
2025-05-28 10:51:32,737 - ERROR - services.scheduler - Error checking notification times for user 380675615: too many values to unpack (expected 2)
2025-05-28 10:52:32,741 - WARNING - utils.helpers - Сет 'The Natural World' не существует для уровня C1 или не соответствует уровню. Путь: levels/C1/The Natural World.txt
2025-05-28 10:52:32,741 - ERROR - services.scheduler - Error checking notification times for user 380675615: too many values to unpack (expected 2)
2025-05-28 10:53:17,379 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 10:53:17,384 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 10:53:17,384 - INFO - __main__ - Бот успешно запущен.
2025-05-28 10:55:10,693 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 10:55:10,695 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 10:55:10,696 - INFO - __main__ - Бот успешно запущен.
2025-05-28 10:55:11,535 - ERROR - aiogram.dispatcher.dispatcher - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiohttp/client.py", line 586, in _request
    await resp.start(conn)
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 905, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olegb/project/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [Errno 104] Connection reset by peer
2025-05-28 10:56:26,911 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 10:56:26,914 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 10:56:26,921 - INFO - __main__ - Бот успешно запущен.
2025-05-28 11:22:53,375 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 11:22:53,539 - INFO - __main__ - Восстановлено 2 уведомлений
2025-05-28 11:22:53,540 - INFO - __main__ - Бот успешно запущен.
2025-05-28 11:23:34,850 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 11:23:34,851 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 11:23:34,853 - INFO - __main__ - Бот успешно запущен.
2025-05-28 11:24:08,457 - WARNING - utils.subscription_helpers - Could not determine level for set Describing People
2025-05-28 11:24:08,458 - WARNING - utils.subscription_helpers - Could not determine level for set Directions & Locations
2025-05-28 11:24:08,458 - WARNING - utils.subscription_helpers - Could not determine level for set Eating Out
2025-05-28 11:24:08,459 - WARNING - utils.subscription_helpers - Could not determine level for set Emotions & Feelings
2025-05-28 11:24:08,459 - WARNING - utils.subscription_helpers - Could not determine level for set Everyday Activities & Routines
2025-05-28 11:24:08,459 - WARNING - utils.subscription_helpers - Could not determine level for set Festivals & Celebrations
2025-05-28 11:24:08,459 - WARNING - utils.subscription_helpers - Could not determine level for set Household Objects
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set In the City
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set Jobs and Occupations
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set Leisure & Free Time
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set Shopping and Money
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set Sports & Hobbies
2025-05-28 11:24:08,460 - WARNING - utils.subscription_helpers - Could not determine level for set Travel Essentials
2025-05-28 11:24:08,461 - WARNING - utils.subscription_helpers - Could not determine level for set Weather & Nature
2025-05-28 11:24:26,012 - ERROR - services.payment - Error creating payment for user 1999873173: {'type': 'error', 'id': '019715fe-2283-7a6f-b6a9-adbfec4220a0', 'code': 'invalid_credentials', 'description': 'Incorrect password format in the Authorization header. Use Secret key issued in Merchant Profile as the password', 'parameter': 'Authorization'}
2025-05-28 11:31:37,111 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 11:31:37,115 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 11:31:37,116 - INFO - __main__ - Бот успешно запущен.
2025-05-28 11:32:11,479 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 11:32:11,481 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 11:32:11,482 - INFO - __main__ - Бот успешно запущен.
2025-05-28 11:32:40,961 - WARNING - utils.subscription_helpers - Could not determine level for set Animals and Pets
2025-05-28 11:32:40,962 - WARNING - utils.subscription_helpers - Could not determine level for set At Home
2025-05-28 11:32:40,963 - WARNING - utils.subscription_helpers - Could not determine level for set Clothes & Accessories
2025-05-28 11:32:40,964 - WARNING - utils.subscription_helpers - Could not determine level for set Common Verbs & Actions
2025-05-28 11:32:40,965 - WARNING - utils.subscription_helpers - Could not determine level for set Days, Months, Seasons
2025-05-28 11:32:40,965 - WARNING - utils.subscription_helpers - Could not determine level for set Essential Everyday Words
2025-05-28 11:32:40,966 - WARNING - utils.subscription_helpers - Could not determine level for set Family and Friends
2025-05-28 11:32:40,966 - WARNING - utils.subscription_helpers - Could not determine level for set Food Basics
2025-05-28 11:32:40,966 - WARNING - utils.subscription_helpers - Could not determine level for set My Body & Health
2025-05-28 11:32:40,967 - WARNING - utils.subscription_helpers - Could not determine level for set Numbers, Colors & Shapes
2025-05-28 11:32:40,967 - WARNING - utils.subscription_helpers - Could not determine level for set School Essentials
2025-05-28 11:32:40,967 - WARNING - utils.subscription_helpers - Could not determine level for set Transport Basics
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set Animals and Pets
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set At Home
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set Clothes & Accessories
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set Common Verbs & Actions
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set Days, Months, Seasons
2025-05-28 11:33:11,786 - WARNING - utils.subscription_helpers - Could not determine level for set Essential Everyday Words
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set Family and Friends
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set Food Basics
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set My Body & Health
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set Numbers, Colors & Shapes
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set School Essentials
2025-05-28 11:33:11,787 - WARNING - utils.subscription_helpers - Could not determine level for set Transport Basics
2025-05-28 11:33:16,787 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Academic Writing
2025-05-28 11:33:16,788 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Environmental Issues
2025-05-28 11:33:16,789 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Legal Vocabulary
2025-05-28 11:33:16,790 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Medical Terms
2025-05-28 11:33:16,791 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Psychology
2025-05-28 11:33:16,792 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Public Speaking & Rhetoric
2025-05-28 11:33:16,792 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Scientific Research
2025-05-28 11:33:16,793 - WARNING - utils.subscription_helpers - Could not determine level for set Art & Cultural Heritage
2025-05-28 11:33:16,795 - WARNING - utils.subscription_helpers - Could not determine level for set Cultural Identity & Diversity
2025-05-28 11:33:16,796 - WARNING - utils.subscription_helpers - Could not determine level for set Diplomacy & International Relations
2025-05-28 11:33:16,797 - WARNING - utils.subscription_helpers - Could not determine level for set Ethics & Moral Dilemmas
2025-05-28 11:33:16,797 - WARNING - utils.subscription_helpers - Could not determine level for set Global Economy & Finance
2025-05-28 11:33:16,798 - WARNING - utils.subscription_helpers - Could not determine level for set High-level Business Terminology
2025-05-28 11:33:16,799 - WARNING - utils.subscription_helpers - Could not determine level for set Historical Analysis & Interpretation
2025-05-28 11:33:16,800 - WARNING - utils.subscription_helpers - Could not determine level for set Innovations & Future Trends
2025-05-28 11:33:16,801 - WARNING - utils.subscription_helpers - Could not determine level for set Language & Linguistics
2025-05-28 11:33:16,801 - WARNING - utils.subscription_helpers - Could not determine level for set Literary Analysis & Criticism
2025-05-28 11:33:16,802 - WARNING - utils.subscription_helpers - Could not determine level for set Native-level Idioms & Expressions
2025-05-28 11:33:16,803 - WARNING - utils.subscription_helpers - Could not determine level for set Philosophy & Existential Questions
2025-05-28 11:33:16,803 - WARNING - utils.subscription_helpers - Could not determine level for set Sociopolitical Commentary
2025-05-28 11:34:18,320 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Academic Writing
2025-05-28 11:34:18,320 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Environmental Issues
2025-05-28 11:34:18,320 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Legal Vocabulary
2025-05-28 11:34:18,320 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Medical Terms
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Psychology
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Public Speaking & Rhetoric
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Scientific Research
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Art & Cultural Heritage
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Cultural Identity & Diversity
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Diplomacy & International Relations
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Ethics & Moral Dilemmas
2025-05-28 11:34:18,321 - WARNING - utils.subscription_helpers - Could not determine level for set Global Economy & Finance
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set High-level Business Terminology
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Historical Analysis & Interpretation
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Innovations & Future Trends
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Language & Linguistics
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Literary Analysis & Criticism
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Native-level Idioms & Expressions
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Philosophy & Existential Questions
2025-05-28 11:34:18,322 - WARNING - utils.subscription_helpers - Could not determine level for set Sociopolitical Commentary
2025-05-28 11:34:24,070 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Academic Writing
2025-05-28 11:34:24,070 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Environmental Issues
2025-05-28 11:34:24,070 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Legal Vocabulary
2025-05-28 11:34:24,070 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Medical Terms
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Psychology
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Public Speaking & Rhetoric
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Scientific Research
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Art & Cultural Heritage
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Cultural Identity & Diversity
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Diplomacy & International Relations
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Ethics & Moral Dilemmas
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Global Economy & Finance
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set High-level Business Terminology
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Historical Analysis & Interpretation
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Innovations & Future Trends
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Language & Linguistics
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Literary Analysis & Criticism
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Native-level Idioms & Expressions
2025-05-28 11:34:24,071 - WARNING - utils.subscription_helpers - Could not determine level for set Philosophy & Existential Questions
2025-05-28 11:34:24,072 - WARNING - utils.subscription_helpers - Could not determine level for set Sociopolitical Commentary
2025-05-28 12:46:05,696 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 12:46:05,829 - INFO - __main__ - Восстановлено 12 уведомлений
2025-05-28 12:46:05,830 - INFO - __main__ - Бот успешно запущен.
2025-05-28 12:50:30,029 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 12:50:30,041 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 12:50:30,042 - INFO - __main__ - Бот успешно запущен.
2025-05-28 12:53:24,041 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 12:53:24,057 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 12:53:24,058 - INFO - __main__ - Бот успешно запущен.
2025-05-28 12:55:54,127 - INFO - __main__ - Проверка пропущенных уведомлений…
2025-05-28 12:55:54,133 - INFO - __main__ - Восстановлено 0 уведомлений
2025-05-28 12:55:54,133 - INFO - __main__ - Бот успешно запущен.
2025-05-28 12:56:16,063 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Academic Writing
2025-05-28 12:56:16,063 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Environmental Issues
2025-05-28 12:56:16,064 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Legal Vocabulary
2025-05-28 12:56:16,064 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Medical Terms
2025-05-28 12:56:16,064 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Psychology
2025-05-28 12:56:16,065 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Public Speaking & Rhetoric
2025-05-28 12:56:16,065 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Scientific Research
2025-05-28 12:56:16,066 - WARNING - utils.subscription_helpers - Could not determine level for set Art & Cultural Heritage
2025-05-28 12:56:16,067 - WARNING - utils.subscription_helpers - Could not determine level for set Cultural Identity & Diversity
2025-05-28 12:56:16,067 - WARNING - utils.subscription_helpers - Could not determine level for set Diplomacy & International Relations
2025-05-28 12:56:16,067 - WARNING - utils.subscription_helpers - Could not determine level for set Ethics & Moral Dilemmas
2025-05-28 12:56:16,068 - WARNING - utils.subscription_helpers - Could not determine level for set Global Economy & Finance
2025-05-28 12:56:16,068 - WARNING - utils.subscription_helpers - Could not determine level for set High-level Business Terminology
2025-05-28 12:56:16,068 - WARNING - utils.subscription_helpers - Could not determine level for set Historical Analysis & Interpretation
2025-05-28 12:56:16,069 - WARNING - utils.subscription_helpers - Could not determine level for set Innovations & Future Trends
2025-05-28 12:56:16,069 - WARNING - utils.subscription_helpers - Could not determine level for set Language & Linguistics
2025-05-28 12:56:16,070 - WARNING - utils.subscription_helpers - Could not determine level for set Literary Analysis & Criticism
2025-05-28 12:56:16,070 - WARNING - utils.subscription_helpers - Could not determine level for set Native-level Idioms & Expressions
2025-05-28 12:56:16,070 - WARNING - utils.subscription_helpers - Could not determine level for set Philosophy & Existential Questions
2025-05-28 12:56:16,071 - WARNING - utils.subscription_helpers - Could not determine level for set Sociopolitical Commentary
2025-05-28 12:56:40,865 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Academic Writing
2025-05-28 12:56:40,866 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Environmental Issues
2025-05-28 12:56:40,870 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Legal Vocabulary
2025-05-28 12:56:40,870 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Medical Terms
2025-05-28 12:56:40,870 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Psychology
2025-05-28 12:56:40,870 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Public Speaking & Rhetoric
2025-05-28 12:56:40,871 - WARNING - utils.subscription_helpers - Could not determine level for set Advanced Scientific Research
2025-05-28 12:56:40,871 - WARNING - utils.subscription_helpers - Could not determine level for set Art & Cultural Heritage
2025-05-28 12:56:40,872 - WARNING - utils.subscription_helpers - Could not determine level for set Cultural Identity & Diversity
2025-05-28 12:56:40,872 - WARNING - utils.subscription_helpers - Could not determine level for set Diplomacy & International Relations
2025-05-28 12:56:40,872 - WARNING - utils.subscription_helpers - Could not determine level for set Ethics & Moral Dilemmas
2025-05-28 12:56:40,873 - WARNING - utils.subscription_helpers - Could not determine level for set Global Economy & Finance
2025-05-28 12:56:40,873 - WARNING - utils.subscription_helpers - Could not determine level for set High-level Business Terminology
2025-05-28 12:56:40,873 - WARNING - utils.subscription_helpers - Could not determine level for set Historical Analysis & Interpretation
2025-05-28 12:56:40,873 - WARNING - utils.subscription_helpers - Could not determine level for set Innovations & Future Trends
2025-05-28 12:56:40,873 - WARNING - utils.subscription_helpers - Could not determine level for set Language & Linguistics
2025-05-28 12:56:40,874 - WARNING - utils.subscription_helpers - Could not determine level for set Literary Analysis & Criticism
2025-05-28 12:56:40,874 - WARNING - utils.subscription_helpers - Could not determine level for set Native-level Idioms & Expressions
2025-05-28 12:56:40,874 - WARNING - utils.subscription_helpers - Could not determine level for set Philosophy & Existential Questions
2025-05-28 12:56:40,874 - WARNING - utils.subscription_helpers - Could not determine level for set Sociopolitical Commentary
